/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "muxkuopsbkkmbvxwlxmb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11eGt1b3BzYmtrbWJ2eHdseG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTUxMjIsImV4cCI6MjA3Mzg3MTEyMn0.-4WSEu0MIlDAD42S3eWtPtTTn_00EKUTxTtfciPi1BE"